# Generated by Django 3.2.5 on 2021-07-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('admissao', models.DateField(verbose_name='Data de admissão')),
                ('preferencia', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia de folga preferencial')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')])),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')])),
            ],
            options={
                'verbose_name': 'Posto de trabalho',
                'verbose_name_plural': 'Postos de trabalho',
            },
        ),
        migrations.CreateModel(
            name='Folga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia de folga')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'folga',
                'verbose_name_plural': 'folgas',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Dia de expediente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.medico', verbose_name='Médico')),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.posto', verbose_name='Posto de trabalho')),
            ],
            options={
                'verbose_name': 'escala',
                'verbose_name_plural': 'escalas',
            },
        ),
    ]
